guru:
  jms:
    username: JMS Username
    password: JMS Password
    url:  JML Url
# 3 dashes are used as file separator 
---
spring:  profiles: deguru:
  jms:
    username: JMS VINCENZEN!